version: "3.8"

services:
    app:
        image: bot
        env_file: .env
        ports:
            - ${server_port}:${server_port}
        restart: "no"
        volumes:
            - ./servers:/bot/servers
            - ./dist:/bot/dist
            - ./website/dist:/bot/public
        build:
          context: .
          dockerfile: Dockerfile.dev
    mongo:
        image: mongo
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
